"""add instruments banks platforms accounts redesign transactions

Revision ID: 5167bb2fefc1
Revises: e8025f73c35a
Create Date: 2026-04-28 17:14:37.477401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260428171437'
down_revision: Union[str, Sequence[str], None] = '20260428122953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_short_name'), 'banks', ['short_name'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', postgresql.ENUM('stock', 'mutual_fund', 'fixed_deposit', 'gold', 'crypto', 'ppf', 'nps', 'real_estate', name='investment_type', create_type=False), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('fund_house', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=False)
    op.create_index(op.f('ix_instruments_type'), 'instruments', ['type'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('broker', 'mf_platform', 'direct', 'other', name='platform_type'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_short_name'), 'platforms', ['short_name'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.Enum('savings', 'current', 'salary', 'nre', 'nro', name='account_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_user_id'), 'platform_accounts', ['user_id'], unique=False)
    op.create_table('user_instruments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'instrument_id')
    )
    op.add_column('investments', sa.Column('platform_account_id', sa.Integer(), nullable=True))
    op.add_column('investments', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_investments_instrument_id'), 'investments', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_investments_platform_account_id'), 'investments', ['platform_account_id'], unique=False)
    op.create_foreign_key(None, 'investments', 'instruments', ['instrument_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'investments', 'platform_accounts', ['platform_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_instrument_id'), 'transactions', ['instrument_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'instruments', ['instrument_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transactions', 'category')

    # Migrate transaction_type enum: income/expense → inbound/outbound
    op.execute("ALTER TABLE transactions ALTER COLUMN type TYPE varchar(20)")
    op.execute("UPDATE transactions SET type = 'inbound' WHERE type = 'income'")
    op.execute("UPDATE transactions SET type = 'outbound' WHERE type = 'expense'")
    op.execute("DROP TYPE transaction_type")
    op.execute("CREATE TYPE transaction_type AS ENUM ('inbound', 'outbound')")
    op.execute(
        "ALTER TABLE transactions ALTER COLUMN type "
        "TYPE transaction_type USING type::transaction_type"
    )
    op.execute("DROP TYPE IF EXISTS transaction_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', postgresql.ENUM('food', 'transport', 'utilities', 'healthcare', 'entertainment', 'shopping', 'education', 'rent', 'salary', 'freelance', 'investment_return', 'other', name='transaction_category'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_instrument_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_column('transactions', 'instrument_id')
    op.drop_column('transactions', 'account_id')
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_index(op.f('ix_investments_platform_account_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_instrument_id'), table_name='investments')
    op.drop_column('investments', 'instrument_id')
    op.drop_column('investments', 'platform_account_id')
    op.drop_table('user_instruments')
    op.drop_index(op.f('ix_platform_accounts_user_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_platforms_short_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_instruments_type'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_banks_short_name'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
