"""revert_transaction_date_to_date_add_composite_index

Revision ID: 20260504195408
Revises: 20260504182657
Create Date: 2026-05-04 19:54:08.167145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260504195408'
down_revision: Union[str, Sequence[str], None] = '20260504182657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.create_index('ix_transactions_date_id', 'transactions', ['date', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_date_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.alter_column('transactions', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
