"""remove ticker_symbol exchange fund_house from investments

Revision ID: a98f6a8ed003
Revises: 5167bb2fefc1
Create Date: 2026-05-03 12:26:48.152577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260503122648'
down_revision: Union[str, Sequence[str], None] = '20260428171437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'exchange')
    op.drop_column('investments', 'ticker_symbol')
    op.drop_column('investments', 'fund_house')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('fund_house', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('investments', sa.Column('ticker_symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('investments', sa.Column('exchange', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
