"""transaction_public_id_uuid_to_string

Revision ID: 20260504124938
Revises: 20260504124023
Create Date: 2026-05-04 12:49:38.563880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260504124938'
down_revision: Union[str, Sequence[str], None] = '20260504124023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'public_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'public_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
